### ISSUE TITLE
can i use  this lib  as this like what i  do in golang? 

### ISSUE THREAD

**Issue by sudavida** [MiSo1289/asiochan#6]
for (;;){
 select {
   case: a<<chan1;
   case: b<<chan2;
       ..........
  }
}

i want to  handle all the data in chann1 and chanl2 ，not discard any one

**Comment by MiSo1289** [comment]
Yes, see the [`select function`](https://github.com/MiSo1289/asiochan#select) in the README; no results should be discarded.

Btw, new versions of ASIO have a native channel type now along with `&&`, `||` operators on awaitables, so maybe the same functionality can be obtained without this library now, but I am not sure if the semantics will be entirely the same (if results can get discarded if reading multiple channels with `||`).

**Comment by sudavida** [comment]
thank you for your answer！and then i should learn how to use asio channel.
&nbsp;


非常道
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Michal ***@***.***&gt;; 
发送时间: 2022年6月2日(星期四) 下午3:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MiSo1289/asiochan] can i use  this lib  as this like what i  do in golang?  (Issue #6)





 
Yes, see the select function in the README; no results should be discarded.
 
Btw, new versions of ASIO have a native channel type now along with &amp;&amp;, || operators on awaitables, so maybe the same functionality can be obtained without this library now, but I am not sure if the semantics will be entirely the same (if results can get discarded if reading multiple channels with ||).
